[2025-08-03T11:25:28.459+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.current_etl.convert_current manual__2025-08-03T11:09:53+00:00 [queued]>
[2025-08-03T11:25:28.476+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.current_etl.convert_current manual__2025-08-03T11:09:53+00:00 [queued]>
[2025-08-03T11:25:28.477+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-03T11:25:28.499+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): current_etl.convert_current> on 2025-08-03 11:09:53+00:00
[2025-08-03T11:25:28.506+0000] {standard_task_runner.py:60} INFO - Started process 221 to run task
[2025-08-03T11:25:28.513+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'current_etl.convert_current', 'manual__2025-08-03T11:09:53+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmpx284uch2']
[2025-08-03T11:25:28.518+0000] {standard_task_runner.py:88} INFO - Job 267: Subtask current_etl.convert_current
[2025-08-03T11:25:28.602+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.current_etl.convert_current manual__2025-08-03T11:09:53+00:00 [running]> on host fce0ae18e39f
[2025-08-03T11:25:28.920+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='current_etl.convert_current' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T11:09:53+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T11:09:53+00:00'
[2025-08-03T11:25:28.923+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/convert_current.py", line 8, in convert_current_nc_to_csv
    os.makedirs(output_folder, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/csv/current'
[2025-08-03T11:25:28.942+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=current_etl.convert_current, execution_date=20250803T110953, start_date=20250803T112528, end_date=20250803T112528
[2025-08-03T11:25:28.959+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 267 for task current_etl.convert_current ([Errno 13] Permission denied: '/opt/airflow/csv/current'; 221)
[2025-08-03T11:25:29.007+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T11:25:29.059+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
