[2025-08-03T07:08:56.374+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.current_etl.load_current manual__2025-08-03T06:41:01+00:00 [queued]>
[2025-08-03T07:08:56.390+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.current_etl.load_current manual__2025-08-03T06:41:01+00:00 [queued]>
[2025-08-03T07:08:56.391+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-03T07:08:56.413+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): current_etl.load_current> on 2025-08-03 06:41:01+00:00
[2025-08-03T07:08:56.421+0000] {standard_task_runner.py:60} INFO - Started process 495 to run task
[2025-08-03T07:08:56.431+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'current_etl.load_current', 'manual__2025-08-03T06:41:01+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmpirnkejwg']
[2025-08-03T07:08:56.438+0000] {standard_task_runner.py:88} INFO - Job 252: Subtask current_etl.load_current
[2025-08-03T07:08:56.510+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.current_etl.load_current manual__2025-08-03T06:41:01+00:00 [running]> on host e2f3b0101b9e
[2025-08-03T07:08:56.950+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='current_etl.load_current' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T06:41:01+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T06:41:01+00:00'
[2025-08-03T07:08:58.673+0000] {logging_mixin.py:188} INFO - âœ… Loaded current to DuckDB: chanthaburi_1_current
[2025-08-03T07:08:58.675+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/load_current_to_duckdb.py", line 14, in load_current_csv_to_duckdb
    con.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM read_csv_auto('{path}');")
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "1"
[2025-08-03T07:08:58.695+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=current_etl.load_current, execution_date=20250803T064101, start_date=20250803T070856, end_date=20250803T070858
[2025-08-03T07:08:58.714+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 252 for task current_etl.load_current (Parser Error: syntax error at or near "1"; 495)
[2025-08-03T07:08:58.748+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T07:08:58.779+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
