[2025-08-02T12:03:03.550+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.thetao_etl.download_thetao scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-08-02T12:03:03.564+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.thetao_etl.download_thetao scheduled__2025-07-20T00:00:00+00:00 [queued]>
[2025-08-02T12:03:03.565+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-02T12:03:03.598+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): thetao_etl.download_thetao> on 2025-07-20 00:00:00+00:00
[2025-08-02T12:03:03.603+0000] {standard_task_runner.py:60} INFO - Started process 106 to run task
[2025-08-02T12:03:03.610+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'thetao_etl.download_thetao', 'scheduled__2025-07-20T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmpxfett6yp']
[2025-08-02T12:03:03.617+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask thetao_etl.download_thetao
[2025-08-02T12:03:03.703+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.thetao_etl.download_thetao scheduled__2025-07-20T00:00:00+00:00 [running]> on host 2376c0e44f50
[2025-08-02T12:03:04.134+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='thetao_etl.download_thetao' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-20T00:00:00+00:00'
[2025-08-02T12:03:04.138+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/download_thetao.py", line 7, in download_thetao
    os.makedirs(output_dir, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/csv/thetao'
[2025-08-02T12:03:04.156+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=thetao_etl.download_thetao, execution_date=20250720T000000, start_date=20250802T120303, end_date=20250802T120304
[2025-08-02T12:03:04.173+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task thetao_etl.download_thetao ([Errno 2] No such file or directory: '/opt/airflow/csv/thetao'; 106)
[2025-08-02T12:03:04.224+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T12:03:04.273+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
