[2025-08-03T11:25:03.964+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.sst_etl.convert_sst manual__2025-08-03T11:09:53+00:00 [queued]>
[2025-08-03T11:25:03.978+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.sst_etl.convert_sst manual__2025-08-03T11:09:53+00:00 [queued]>
[2025-08-03T11:25:03.978+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-03T11:25:03.998+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): sst_etl.convert_sst> on 2025-08-03 11:09:53+00:00
[2025-08-03T11:25:04.006+0000] {standard_task_runner.py:60} INFO - Started process 203 to run task
[2025-08-03T11:25:04.012+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'sst_etl.convert_sst', 'manual__2025-08-03T11:09:53+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmpzwhsjxhh']
[2025-08-03T11:25:04.017+0000] {standard_task_runner.py:88} INFO - Job 264: Subtask sst_etl.convert_sst
[2025-08-03T11:25:04.091+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.sst_etl.convert_sst manual__2025-08-03T11:09:53+00:00 [running]> on host fce0ae18e39f
[2025-08-03T11:25:04.401+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='sst_etl.convert_sst' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T11:09:53+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T11:09:53+00:00'
[2025-08-03T11:25:04.405+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/convert_sst.py", line 8, in convert_sst_nc_to_csv
    os.makedirs(output_folder, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/csv/sst'
[2025-08-03T11:25:04.427+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=sst_etl.convert_sst, execution_date=20250803T110953, start_date=20250803T112503, end_date=20250803T112504
[2025-08-03T11:25:04.453+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 264 for task sst_etl.convert_sst ([Errno 13] Permission denied: '/opt/airflow/csv/sst'; 203)
[2025-08-03T11:25:04.506+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T11:25:04.552+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
