[2025-08-02T12:09:30.516+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.sst_etl.download_sst manual__2025-08-02T12:09:23.082188+00:00 [queued]>
[2025-08-02T12:09:30.529+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.sst_etl.download_sst manual__2025-08-02T12:09:23.082188+00:00 [queued]>
[2025-08-02T12:09:30.530+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-02T12:09:30.551+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): sst_etl.download_sst> on 2025-08-02 12:09:23.082188+00:00
[2025-08-02T12:09:30.560+0000] {standard_task_runner.py:60} INFO - Started process 176 to run task
[2025-08-02T12:09:30.566+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'sst_etl.download_sst', 'manual__2025-08-02T12:09:23.082188+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmp77ht6ohs']
[2025-08-02T12:09:30.572+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask sst_etl.download_sst
[2025-08-02T12:09:30.654+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.sst_etl.download_sst manual__2025-08-02T12:09:23.082188+00:00 [running]> on host 2376c0e44f50
[2025-08-02T12:09:31.078+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='sst_etl.download_sst' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T12:09:23.082188+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T12:09:23.082188+00:00'
[2025-08-02T12:09:31.084+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/download_sst.py", line 7, in download_sst
    os.makedirs(output_dir, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/csv/sst'
[2025-08-02T12:09:31.106+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=sst_etl.download_sst, execution_date=20250802T120923, start_date=20250802T120930, end_date=20250802T120931
[2025-08-02T12:09:31.125+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task sst_etl.download_sst ([Errno 2] No such file or directory: '/opt/airflow/csv/sst'; 176)
[2025-08-02T12:09:31.180+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T12:09:31.232+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
