[2025-08-03T06:25:56.204+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.so_etl.download_so manual__2025-08-03T06:15:57+00:00 [queued]>
[2025-08-03T06:25:56.217+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.so_etl.download_so manual__2025-08-03T06:15:57+00:00 [queued]>
[2025-08-03T06:25:56.218+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-03T06:25:56.241+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): so_etl.download_so> on 2025-08-03 06:15:57+00:00
[2025-08-03T06:25:56.248+0000] {standard_task_runner.py:60} INFO - Started process 168 to run task
[2025-08-03T06:25:56.254+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'so_etl.download_so', 'manual__2025-08-03T06:15:57+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmpffoculuu']
[2025-08-03T06:25:56.259+0000] {standard_task_runner.py:88} INFO - Job 230: Subtask so_etl.download_so
[2025-08-03T06:25:56.327+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.so_etl.download_so manual__2025-08-03T06:15:57+00:00 [running]> on host e2f3b0101b9e
[2025-08-03T06:25:56.697+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='so_etl.download_so' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T06:15:57+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T06:15:57+00:00'
[2025-08-03T06:25:56.713+0000] {deprecated_options.py:61} WARNING - 'force_download' has been deprecated.
[2025-08-03T06:26:00.457+0000] {services_utils.py:262} INFO - Selected dataset version: "202406"
[2025-08-03T06:26:00.458+0000] {services_utils.py:286} INFO - Selected dataset part: "default"
[2025-08-03T06:26:04.805+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/download_so.py", line 24, in download_salinity
    subset(
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/core_functions/deprecated_options.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/python_interface/exception_handler.py", line 17, in wrapper
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/python_interface/exception_handler.py", line 13, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/python_interface/subset.py", line 195, in subset
    return subset_function(
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/core_functions/subset.py", line 181, in subset_function
    response = download_zarr(
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/download_functions/download_zarr.py", line 234, in download_zarr
    response = download_dataset(
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/download_functions/download_zarr.py", line 102, in download_dataset
    dataset = open_dataset_from_arco_series(
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/download_functions/download_zarr.py", line 281, in open_dataset_from_arco_series
    dataset = subset(
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/download_functions/subset_xarray.py", line 588, in subset
    dataset = _variables_subset(dataset, variables)
  File "/home/airflow/.local/lib/python3.10/site-packages/copernicusmarine/download_functions/subset_xarray.py", line 520, in _variables_subset
    raise VariableDoesNotExistInTheDataset(variable)
copernicusmarine.core_functions.exceptions.VariableDoesNotExistInTheDataset: The variable 'so' is neither a variable or a standard name in the dataset.
[2025-08-03T06:26:04.831+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=so_etl.download_so, execution_date=20250803T061557, start_date=20250803T062556, end_date=20250803T062604
[2025-08-03T06:26:04.861+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 230 for task so_etl.download_so (The variable 'so' is neither a variable or a standard name in the dataset.; 168)
[2025-08-03T06:26:04.906+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T06:26:04.973+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
