[2025-08-03T11:25:10.686+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marine_data_etl_dag.thetao_etl.convert_thetao manual__2025-08-03T11:09:53+00:00 [queued]>
[2025-08-03T11:25:10.713+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marine_data_etl_dag.thetao_etl.convert_thetao manual__2025-08-03T11:09:53+00:00 [queued]>
[2025-08-03T11:25:10.714+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-03T11:25:10.746+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): thetao_etl.convert_thetao> on 2025-08-03 11:09:53+00:00
[2025-08-03T11:25:10.755+0000] {standard_task_runner.py:60} INFO - Started process 209 to run task
[2025-08-03T11:25:10.763+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marine_data_etl_dag', 'thetao_etl.convert_thetao', 'manual__2025-08-03T11:09:53+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/marine_data_etl_dag.py', '--cfg-path', '/tmp/tmpb8uulaqq']
[2025-08-03T11:25:10.771+0000] {standard_task_runner.py:88} INFO - Job 265: Subtask thetao_etl.convert_thetao
[2025-08-03T11:25:10.897+0000] {task_command.py:423} INFO - Running <TaskInstance: marine_data_etl_dag.thetao_etl.convert_thetao manual__2025-08-03T11:09:53+00:00 [running]> on host fce0ae18e39f
[2025-08-03T11:25:11.554+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='marine_data_etl_dag' AIRFLOW_CTX_TASK_ID='thetao_etl.convert_thetao' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T11:09:53+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T11:09:53+00:00'
[2025-08-03T11:25:11.560+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/convert_thetao.py", line 8, in convert_thetao_nc_to_csv
    os.makedirs(output_folder, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflow/csv/thetao'
[2025-08-03T11:25:11.581+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=marine_data_etl_dag, task_id=thetao_etl.convert_thetao, execution_date=20250803T110953, start_date=20250803T112510, end_date=20250803T112511
[2025-08-03T11:25:11.604+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 265 for task thetao_etl.convert_thetao ([Errno 13] Permission denied: '/opt/airflow/csv/thetao'; 209)
[2025-08-03T11:25:11.664+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T11:25:11.727+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
